# Generated by Django 4.0 on 2022-05-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_item_count_alter_item_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_count',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
