# Generated by Django 4.0 on 2022-05-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_item_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_number',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
